# Generated by Django 3.1.5 on 2021-01-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210124_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/default.jpg', null=True, upload_to=''),
        ),
    ]
